In [1]:
import torch

https://en.wikipedia.org/wiki/Tensor

# Tensors

In [2]:
#rank 2 tensor, 2 axis
tensor = torch.tensor([
    [1,1,1,1],
    [2,2,2,2],
    [3,3,3,3]
], dtype=torch.float)

In [3]:
#rank 2 tensor, 2 axis
tensor2 = torch.tensor([
    [1,1,1,1,1],
    [2,2,2,2,1],
    [3,3,3,3,1],
    [4,4,4,4,4]
], dtype=torch.float)

# Shapes

In [4]:
#Heigh 3, length 4
tensor.size()

torch.Size([3, 4])

In [5]:
#Heigh 3, length 4
tensor2.size()

torch.Size([4, 5])

In [6]:
#Same as size
tensor.shape

torch.Size([3, 4])

In [7]:
#Same as size
tensor2.shape

torch.Size([4, 5])

In [8]:
#2 Dimensions
len(tensor.shape)

2

In [9]:
#2 Dimensions
len(tensor2.shape)

2

In [10]:
#Tensor has 12 components. Scalar compnonents
torch.tensor(tensor.shape).prod()

tensor(12)

In [11]:
#Same as taking the product of the shape
tensor.numel()

12

# Reshaping

tensor.numel() = 12, therfore all reshapes are factors of 12

In [12]:
tensor.reshape(1,12)

tensor([[1., 1., 1., 1., 2., 2., 2., 2., 3., 3., 3., 3.]])

In [13]:
tensor.reshape(2,6)

tensor([[1., 1., 1., 1., 2., 2.],
        [2., 2., 3., 3., 3., 3.]])

In [14]:
tensor.reshape(3,4)

tensor([[1., 1., 1., 1.],
        [2., 2., 2., 2.],
        [3., 3., 3., 3.]])

In [15]:
tensor.reshape(6,2)

tensor([[1., 1.],
        [1., 1.],
        [2., 2.],
        [2., 2.],
        [3., 3.],
        [3., 3.]])

In [16]:
tensor.reshape(12,1)

tensor([[1.],
        [1.],
        [1.],
        [1.],
        [2.],
        [2.],
        [2.],
        [2.],
        [3.],
        [3.],
        [3.],
        [3.]])

# Reshaping the rank

In [17]:
tensor.reshape(2,2,3)

tensor([[[1., 1., 1.],
         [1., 2., 2.]],

        [[2., 2., 3.],
         [3., 3., 3.]]])

# Squeezing

In [18]:
print(tensor.reshape(1,12))
print(tensor.reshape(1,12).shape)

tensor([[1., 1., 1., 1., 2., 2., 2., 2., 3., 3., 3., 3.]])
torch.Size([1, 12])


In [19]:
print(tensor.reshape(1,12).squeeze())
print(tensor.reshape(1,12).squeeze().shape)

tensor([1., 1., 1., 1., 2., 2., 2., 2., 3., 3., 3., 3.])
torch.Size([12])


In [20]:
print(tensor.reshape(1,12).squeeze().unsqueeze(dim=0))
print(tensor.reshape(1,12).squeeze().unsqueeze(dim=0).shape)

tensor([[1., 1., 1., 1., 2., 2., 2., 2., 3., 3., 3., 3.]])
torch.Size([1, 12])


# Flatten

In [21]:
def flatten(t):
    t = t.reshape(1,-1) #-1 will automatically find the right value for reshaping
    t = t.squeeze() #converts to a 1d array
    return t

In [22]:
flatten(tensor)

tensor([1., 1., 1., 1., 2., 2., 2., 2., 3., 3., 3., 3.])

In [23]:
tensor.reshape(1,12)

tensor([[1., 1., 1., 1., 2., 2., 2., 2., 3., 3., 3., 3.]])

# Image tensor

In [24]:
flattentensor = torch.tensor([
    [1,1,1,1],
    [1,1,1,1],
    [1,1,1,1],
    [1,1,1,1]
])

In [25]:
flattentensor2 = torch.tensor([
    [2,2,2,2],
    [2,2,2,2],
    [2,2,2,2],
    [2,2,2,2]
])

In [26]:
flattentensor3 = torch.tensor([
    [3,3,3,3],
    [3,3,3,3],
    [3,3,3,3],
    [3,3,3,3]
])

In [27]:
t = torch.stack((flattentensor,flattentensor2,flattentensor3))
t.shape 

torch.Size([3, 4, 4])

3, 4, 4 = batchsize, height, width

In [28]:
t

tensor([[[1, 1, 1, 1],
         [1, 1, 1, 1],
         [1, 1, 1, 1],
         [1, 1, 1, 1]],

        [[2, 2, 2, 2],
         [2, 2, 2, 2],
         [2, 2, 2, 2],
         [2, 2, 2, 2]],

        [[3, 3, 3, 3],
         [3, 3, 3, 3],
         [3, 3, 3, 3],
         [3, 3, 3, 3]]])

# Color channel

In [29]:
t = t.reshape(3,1,4,4)
t

tensor([[[[1, 1, 1, 1],
          [1, 1, 1, 1],
          [1, 1, 1, 1],
          [1, 1, 1, 1]]],


        [[[2, 2, 2, 2],
          [2, 2, 2, 2],
          [2, 2, 2, 2],
          [2, 2, 2, 2]]],


        [[[3, 3, 3, 3],
          [3, 3, 3, 3],
          [3, 3, 3, 3],
          [3, 3, 3, 3]]]])

In [30]:
t[0] #acess first tensor

tensor([[[1, 1, 1, 1],
         [1, 1, 1, 1],
         [1, 1, 1, 1],
         [1, 1, 1, 1]]])

In [31]:
t[0][0] #acess first colorchannel

tensor([[1, 1, 1, 1],
        [1, 1, 1, 1],
        [1, 1, 1, 1],
        [1, 1, 1, 1]])

In [32]:
t[0][0][0] #acess first line

tensor([1, 1, 1, 1])

In [33]:
t[0][0][0][0] #acess fires pixel

tensor(1)

# flatten image

In [34]:
t.reshape(1,-1)[0]

tensor([1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 2, 2, 2, 2, 2, 2, 2,
        2, 2, 2, 2, 2, 2, 2, 2, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3])

In [35]:
t.reshape(-1)

tensor([1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 2, 2, 2, 2, 2, 2, 2,
        2, 2, 2, 2, 2, 2, 2, 2, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3])

In [36]:
t.view(t.numel())

tensor([1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 2, 2, 2, 2, 2, 2, 2,
        2, 2, 2, 2, 2, 2, 2, 2, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3])

In [37]:
t.flatten()

tensor([1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 2, 2, 2, 2, 2, 2, 2,
        2, 2, 2, 2, 2, 2, 2, 2, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3])

In [38]:
t.flatten(start_dim=1).shape

torch.Size([3, 16])

In [39]:
t.flatten(start_dim=1)

tensor([[1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
        [2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2],
        [3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3]])

# Element-wise operations

In [40]:
elementtensor = torch.tensor([[1,2],
                              [3,4]], dtype=torch.float32)

elementtensor2 = torch.tensor([[9,8],
                               [7,6]], dtype=torch.float32)

In [41]:
elementtensor[0]

tensor([1., 2.])

In [42]:
elementtensor[0][0]

tensor(1.)

In [43]:
elementtensor + elementtensor2

tensor([[10., 10.],
        [10., 10.]])

In [44]:
elementtensor - elementtensor2

tensor([[-8., -6.],
        [-4., -2.]])

In [45]:
elementtensor * elementtensor2

tensor([[ 9., 16.],
        [21., 24.]])

In [46]:
elementtensor3 = torch.tensor([
    [0,5,7],
    [6,0,7],
    [0,8,0]
], dtype=torch.float32)

In [47]:
elementtensor3.eq(0)

tensor([[ True, False, False],
        [False,  True, False],
        [ True, False,  True]])

In [48]:
elementtensor3.ge(0)

tensor([[True, True, True],
        [True, True, True],
        [True, True, True]])

In [49]:
elementtensor3.gt(0)

tensor([[False,  True,  True],
        [ True, False,  True],
        [False,  True, False]])

In [50]:
elementtensor3.lt(0)

tensor([[False, False, False],
        [False, False, False],
        [False, False, False]])

In [51]:
elementtensor3.le(7)

tensor([[ True,  True,  True],
        [ True,  True,  True],
        [ True, False,  True]])

In [52]:
elementtensor3.abs()

tensor([[0., 5., 7.],
        [6., 0., 7.],
        [0., 8., 0.]])

In [53]:
elementtensor3.sqrt()

tensor([[0.0000, 2.2361, 2.6458],
        [2.4495, 0.0000, 2.6458],
        [0.0000, 2.8284, 0.0000]])

In [54]:
elementtensor3.neg()

tensor([[-0., -5., -7.],
        [-6., -0., -7.],
        [-0., -8., -0.]])

In [55]:
elementtensor3.neg().abs()

tensor([[0., 5., 7.],
        [6., 0., 7.],
        [0., 8., 0.]])

# Reduction operations

In [56]:
newtensor = torch.tensor([
    [0,1,0],
    [2,0,2],
    [0,3,0]
], dtype=torch.float32)

In [57]:
newtensor.sum() #Sum of scalars

tensor(8.)

In [58]:
newtensor.numel() #Sum of elements

9

In [59]:
newtensor.sum().numel()

1

In [60]:
newtensor.sum().numel() < newtensor.numel()

True

In [61]:
newtensor.prod()

tensor(0.)

In [62]:
newtensor.mean()

tensor(0.8889)

In [63]:
newtensor.std()

tensor(1.1667)

In [64]:
newtensor2 = torch.tensor([
    [1,1,1,1],
    [2,2,2,2],
    [3,3,3,3]
], dtype=torch.float32)

In [65]:
newtensor2.sum(dim=0) #first axis sum

tensor([6., 6., 6., 6.])

In [66]:
newtensor2.sum(dim=1) #second axis sum

tensor([ 4.,  8., 12.])

In [67]:
newtensor3 = torch.tensor([
    [1,0,0,2],
    [0,3,3,0],
    [4,0,0,5]
], dtype=torch.float32)

In [68]:
newtensor3.max() 

tensor(5.)

In [69]:
newtensor3.argmax()

tensor(11)

In [70]:
newtensor3.flatten() #argmax value from the flatten tensor

tensor([1., 0., 0., 2., 0., 3., 3., 0., 4., 0., 0., 5.])

In [71]:
newtensor3.max(dim=0)

torch.return_types.max(
values=tensor([4., 3., 3., 5.]),
indices=tensor([2, 1, 1, 2]))

In [72]:
newtensor3.argmax(dim=0)

tensor([2, 1, 1, 2])

In [73]:
newtensor3.max(dim=1)

torch.return_types.max(
values=tensor([2., 3., 5.]),
indices=tensor([3, 1, 3]))

In [74]:
newtensor3.argmax(dim=1)

tensor([3, 1, 3])